colorscheme slate
set hidden	"can change buffers without writing, stores changes
set backspace=indent,eol,start	"makes backspace act like normal
set ruler  
set tabstop=4	"tab = 4 spaces
set showcmd
set number		"show line numbers
set showmatch	"show matching parenthesis
set autoindent
set copyindent		"copy previous indentation for auto indent
set shiftwidth=4	"spaces to autoindent
set smarttab		"inset tabs on beginning of line using shiftwidth

set history=1000 	"commands and search history
set undolevels=1000	"number o fhistory for undo
set title 			"terminal title

set nobackup
set noswapfile

filetype plugin on
syntax on
execute pathogen#infect()

"with a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
nnoremap ; :
let mapleader = ","
let g:mapleader = ","
" Fast saving
nmap <leader>w :w!<cr>
nmap <leader>q :q!<cr>
nmap <leader>wq :wq!<cr>
"Fast Buffers
nnoremap <Leader>p :bp<CR>
nnoremap <Leader>n :bn<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>
 
"Fast Search and replace
nmap fr :%s/

"EASYMOTION MAPS
map / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)
" " These `n` & `N` mappings are options. You do not have to map `n` & `N` to
" EasyMotion.
" " Without these mappings, `n` & `N` works fine. (These mappings just provide
" " different highlight method and have some other features )
map n <Plug>(easymotion-next)
map N <Plug>(easymotion-prev)
"CTRL-P FUZZY FINDER MAPS
nmap ff <c-p>
"NERDTREE
nmap nt :NERDTreeToggle<cr>
