"source /apollo/env/envImprovement/var/vimrc
set mouse=a "enable mouse in vim
set incsearch "always one line above and below cursor
set hidden	"can change buffers without writing, stores changes
set backspace=indent,eol,start	"makes backspace act like normal
set ruler  
set showcmd
set number		"show line numbers
set showmatch	"show matching parenthesis
set autoindent
set smartindent
set wrap
set expandtab
set shiftwidth=4	"spaces to autoindent
set tabstop=4	"tab = 4 spaces
set smartcase   " for searching, if you use caps it will look for caps
set ignorecase  " Whenn searching it will ignore caps, if you use caps then ^smart case will make it look for caps
set history=1000 	"commands and search history
set undolevels=1000	"number o fhistory for undo

" These remove backups, annoying files but if vim crashes you lose changes..
set nobackup
set noswapfile

"enable plugins and pathogen
filetype plugin on
syntax on
execute pathogen#infect()

"theme
set background=dark
colorscheme solarized

"colorscheme distinguished

"with a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
 nnoremap ; :
 let mapleader = ","
 let g:mapleader = ","

" Fast saving
nmap <leader>w :w!<cr>
nmap <leader>q :q!<cr>
nmap <leader>wq :wq!<cr>


"Fast Search and replace
nmap fr :%s/


"EASYMOTION MAPS
" Gif config
 map  / <Plug>(easymotion-sn)
 omap / <Plug>(easymotion-tn)

" " These `n` & `N` mappings are options. You do not have to map `n` & `N` to
" EasyMotion.
" " Without these mappings, `n` & `N` works fine. (These mappings just provide
" " different highlight method and have some other features )
 map  n <Plug>(easymotion-next)
 map  N <Plug>(easymotion-prev)


"CTRL-P FUZZY FINDER MAPS
nmap ff <c-p>

"NERDTREE
nmap nt :NERDTreeToggle<cr>

"TagBar
nmap tt :TagbarToggle<CR>

"Fast Buffers
nnoremap <Leader>p :bp<cr>
nnoremap <Leader>n :bn<cr>

"Neocomplete
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1

" Define dictionary.
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'vimshell' : $HOME.'/.vimshell_hist',
    \ 'scheme' : $HOME.'/.gosh_completions'
        \ }

" Define keyword.
if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'

" Recommended key-mappings.
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  "return neocomplete#close_popup() . "\<CR>"
  " For no inserting <CR> key.
  return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><C-y>  neocomplete#close_popup()
inoremap <expr><C-e>  neocomplete#cancel_popup()


autocmd! FileType c,cpp,java,php call CSyntaxAfter() 
