colorscheme slate

set nocompatible "fixes arrow problems in remote shell

set hidden	"can change buffers without writing, stores changes
set backspace=indent,eol,start	"makes backspace act like normal
set ruler  
set showcmd
set number		"show line numbers
set showmatch	"show matching parenthesis
set autoindent
set smartindent
set wrap

set shiftwidth=4	"spaces to autoindent
set tabstop=4	"tab = 4 spaces


set history=1000 	"commands and search history
set undolevels=1000	"number o fhistory for undo

set nobackup
set noswapfile

filetype plugin on
syntax on
"with a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
 nnoremap ; : 
 let mapleader = ";"
 let g:mapleader = ";"

" Fast saving
nmap <leader>w :w!<cr>
