
" Configuration file for vim
set modelines=0		" CVE-2007-2438

" Don't write backup file if vim is being called by "crontab -e"
au BufWrite /private/tmp/crontab.* set nowritebackup
" Don't write backup file if vim is being called by "chpass"
au BufWrite /private/etc/pw.* set nowritebackup

" User defined settings 
set nocompatible "fixes arrow problems in remote shell

set hidden	"can change buffers without writing, stores changes
set backspace=indent,eol,start	"makes backspace act like normal
set ruler  
set showcmd
set number		"show line numbers
set showmatch	"show matching parenthesis
set autoindent
set smartindent
set wrap

set shiftwidth=4	"spaces to autoindent
set tabstop=4	"tab = 4 spaces


set history=1000 	"commands and search history
set undolevels=1000	"number o fhistory for undo

set nobackup
set noswapfile

filetype plugin on
syntax on

execute pathogen#infect()

"with a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
 nnoremap ; :
 let mapleader = ","
 let g:mapleader = ","

" Fast saving
nmap <leader>w :w!<cr>
nmap <leader>q :q!<cr>
nmap <leader>wq :wq!<cr>


"Fast Buffers
nnoremap <Leader>p :bp<CR>
nnoremap <Leader>n :bn<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>


colorscheme distinguished
